language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get install astyle

install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  
script:
  - python -m pytest --cov=keras2c/

after_success:
  - mv include/*.gc* ./
  - gcov *.gcda
  - rm test__*{.gcov,.gcda,.gcno}
  - codecov

notifications:
